### PR TITLE
Build resctl-demo and run unit tests in GitHub CI

### PR DESCRIPTION
**Pull request by obbardc**
For each pull request, build the project from source then run the test suite.

### CODE REVIEW

**Comment by obbardc** [comment]
Some things left to consider:

Should we run the demo/bench with `--help` or similar to smoke test it in CI ?
Should we upload the artefacts for a tags as a release on GitHub (could be in a follow up MR) ?

**Comment by plv** [comment]
>Should we run the demo/bench with --help or similar to smoke test it in CI ?
>Should we upload the artefacts for a tags as a release on GitHub (could be in a follow up MR) ?

These both sound good to me. Also, could we add a rule that runs `rustfmt` on pull requests? We do something similar in another project [here](https://github.com/facebookincubator/resctl/blob/master/.github/workflows/ci.yml#L10-L23).

**Comment by obbardc** [comment]
Sorry for the delay. I managed to carve some time to take another look.

Please can you allow it to run to see if it works?

**Review by davide125 — APPROVED** [review]

**Comment by obbardc** [comment]
pushed again to simplify the script, can you pls run it?

**Pull request merged**
